version: '3.8'

services:
  backend:
    build:
      context: ./backend # Dockerfile 的上下文路径
      dockerfile: Dockerfile # Dockerfile 的文件名
    ports:
      - "61401:3000" # 将主机的3000端口映射到容器的3000端口
    restart: unless-stopped # 容器退出时总是重启，除非手动停止
    container_name: sub-store-backend # 定义容器名称
    # 可以根据需要添加卷挂载，例如用于持久化数据或开发时的代码热更新
    # volumes:
    #   - ./backend/src:/usr/src/app/src # 挂载代码，用于开发
    #   - sub_store_data:/usr/src/app/data # 假设有数据需要持久化
# volumes: # 如果定义了命名卷，在此处声明
#   sub_store_data: 